### ISSUE TITLE
Feature request: Agenda view or today's task list view

### ISSUE THREAD

**Issue by robinsrk** [theexplay/vscode-infocus#1]
Please add agenda view of the tasks and/or today's task list view where user can find all the tasks pending for today and select as done from there.

**Comment by theexplay** [comment]
Hi, thanks for the suggestion, I'll try to add this functionality in the near future

**Comment by theexplay** [comment]
Added today, upcoming and missed views
![image](https://user-images.githubusercontent.com/8730184/180656383-c0b2cb2f-ff07-483f-809d-463a6ba59f90.png)

**Comment by theexplay** [comment]
Published in 0.3.0 version
