### ISSUE TITLE
(suggestion) Format link to vscode inside of a markdown hyper link

### ISSUE THREAD

**Issue by erauner12** [theexplay/vscode-infocus#4]
I think this one would be useful because sometimes the path is incredible long. If the `vscode://`  link were formatted in such a way to prevent this from happening. I think it could make each todo look much cleaner:

example: `fix this piece of code - [link](vsccode://<path>)`

**Comment by erauner12** [comment]
![](https://github.com/theexplay/vscode-infocus/assets/59383957/192e68b5-4d86-417f-a4cf-9fb9bc5aa0ca)

vs  
  
 

![](https://github.com/theexplay/vscode-infocus/assets/59383957/169d5247-12a6-4269-aac1-e1a619b4fc4c)

**Comment by theexplay** [comment]
Hello,

Thank you for using extension and for sharing your ideas for enhancing it. I will add this functionality in the next couple of weeks.

**Comment by theexplay** [comment]
Hi there @erauner12 ! I've added a new functionality to generate new tasks with markdown-formatted links, while old links will continue to be displayed as before. I'm not sure how well the automatic replacement of such URLs with markdown will work for users, so I implemented it this way. I hope this meets your requirements. If you disagree with this approach, please let me know in this issue or open a new one
![image](https://github.com/theexplay/vscode-infocus/assets/8730184/265cf87a-192f-4e1d-9f38-a2ab69b92579)
![image](https://github.com/theexplay/vscode-infocus/assets/8730184/037b4c03-7c1b-47c3-8c8c-d32d3c95d5f9)

**Comment by theexplay** [comment]
Published in 0.6.0 version
