### ISSUE TITLE
[Feature Request] Ability to add Sub Tasks

### ISSUE THREAD

**Issue by ATXadam** [theexplay/vscode-infocus#6]
Add the ability to add a [Sub Task](https://todoist.com/help/articles/introduction-to-sub-tasks-kMamDo) to a Task.

Currently you can create a Task on a Project or Section, but it appears you cannot create a Task on a Task (sub task)

Ideally, you would be able to click a "+" on a task, type in the task name and it nests the task.
The plugin already renders these nested tags and they work good.

**Comment by theexplay** [comment]
Hello, thank you for your request, I will add this functionality in one or two weeks, as time permits

**Comment by theexplay** [comment]
Hey @ATXadam, just wanted to let you know I've rolled out this feature in version 0.8.0. You can give it a try now! Really hoping the update I've made hits the mark for you. If you have a moment to share your thoughts or how it's working out, I'd love to hear it

**Comment by theexplay** [comment]
![image](https://github.com/theexplay/vscode-infocus/assets/8730184/d5840819-77b9-4332-9698-31b2ab8b1045)
