### ISSUE TITLE
[Feature Request] Better support for Uncompletable Task

### ISSUE THREAD

**Issue by ATXadam** [theexplay/vscode-infocus#7]
Currently, the plugin will render a [Uncompletable](https://todoist.com/help/articles/how-to-create-an-uncompletable-task-QxQosZuF) task as a regular task, and it's Sub Tasks as normal.

**Feature Requests**

- Ability to add tasks to an uncompletable task (A "+" button like in Sections or Projects would be great)
- Uncompletable tasks should be uncompletable; It appears the API lets you complete them
  - Change these uncompletable tasks to a different icon, like a Folder (as you have for a Section?)
  - Do not allow the completion of an uncompletable task

**Comment by theexplay** [comment]
Hello, thank you for your request, I will add this functionality in one or two weeks, as time permits

**Comment by theexplay** [comment]
Hey @ATXadam, just wanted to let you know I've rolled out this feature in version 0.8.0. You can give it a try now! Really hoping the update I've made hits the mark for you. If you have a moment to share your thoughts or how it's working out, I'd love to hear it

**Comment by theexplay** [comment]
![image](https://github.com/theexplay/vscode-infocus/assets/8730184/13ebddac-81b6-4fa9-b6b0-66467cb8c2bf)
Uncompletable Tasks - has a different "folder" icon
